In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("Hello TensorFlow")

In [3]:
sess = tf.Session()

In [4]:
sess.run(hello)

b'Hello TensorFlow'

## 张量
- 张量是用来表示多维数据的
- 执行操作时的输入输出数据
- 用户通过执行操作来创建或计算张量
- 张量的形状不一定在编译时确定，可以在运行时通过形状推断计算得出
"""
tf.constant  常量
tf.placeholder  占位符
tf.Variable  变量
"""

In [5]:
# 0阶张量
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

In [6]:
[mammal, ignition, floating, its_complicated]

[<tf.Variable 'Variable:0' shape=() dtype=string_ref>,
 <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_2:0' shape=() dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=() dtype=complex128_ref>]

- 注意Variable的名称

In [7]:
# 1阶张量
mystr = tf.Variable(["Hello", "World"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

In [8]:
[mystr, cool_numbers, first_primes, its_very_complicated]

[<tf.Variable 'Variable_4:0' shape=(2,) dtype=string_ref>,
 <tf.Variable 'Variable_5:0' shape=(2,) dtype=float32_ref>,
 <tf.Variable 'Variable_6:0' shape=(5,) dtype=int32_ref>,
 <tf.Variable 'Variable_7:0' shape=(2,) dtype=complex128_ref>]

In [9]:
# 2阶张量
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

In [10]:
[mymat, myxor, linear_squares, squarish_squares, rank_of_squares, mymatC]

[<tf.Variable 'Variable_8:0' shape=(2, 1) dtype=int32_ref>,
 <tf.Variable 'Variable_9:0' shape=(2, 2) dtype=bool_ref>,
 <tf.Variable 'Variable_10:0' shape=(4, 1) dtype=int32_ref>,
 <tf.Variable 'Variable_11:0' shape=(2, 2) dtype=int32_ref>,
 <tf.Tensor 'Rank:0' shape=() dtype=int32>,
 <tf.Variable 'Variable_12:0' shape=(2, 1) dtype=int32_ref>]

In [11]:
# 4阶张量
my_image = tf.zeros([10, 299, 299, 3])  # batch x height x width x color

In [12]:
my_image

<tf.Tensor 'zeros:0' shape=(10, 299, 299, 3) dtype=float32>

## 变量Variable

In [14]:
# 创建变量
# tf.random_normal 方法返回形状为(1，4)的张量。它的4个元素符合均值为100、标准差为0.35的正态分布。
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35), name="W")
b = tf.Variable(tf.zeros([4]), name="b")

In [15]:
[W, b]

[<tf.Variable 'W:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b:0' shape=(4,) dtype=float32_ref>]

In [16]:
# 初始化变量
# 创建会话（之后小节介绍）
sess = tf.Session()
# 使用 global_variables_initializer 方法初始化全局变量 W 和 b
sess.run(tf.global_variables_initializer())
# 执行操作，获取变量值
sess.run([W, b])

[array([[100.31355, 100.47182,  99.95023, 100.13972]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [17]:
# 执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))

array([1., 1., 1., 1.], dtype=float32)

In [18]:
# 查看变量 b 是否更新成功
sess.run(b)

array([1., 1., 1., 1.], dtype=float32)

## Saver 使用示例
```PYTHON
v1 = tf.Variable(..., name='v1')
v2 = tf.Variable(..., name='v2')
# 指定需要保存和恢复的变量
saver = tf.train.Saver({'v1': v1, 'v2': v2})
saver = tf.train.Saver([v1, v2])
saver = tf.train.Saver({v.op.name: v for v in [v1, v2]})
# 保存变量的方法
tf.train.saver.save(sess, 'my-model', global_step=0) # ==> filename: 'my-model-0'
```

In [20]:
# 创建Saver
saver = tf.train.Saver({'W': W, 'b': b})
# 存储变量到文件 './summary/test.ckpt-0'
saver.save(sess, './summary/test.ckpt', global_step=0)

'./summary/test.ckpt-0'

In [21]:
# 再次执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))
# 获取变量 b 的最新值
sess.run(b)

array([2., 2., 2., 2.], dtype=float32)

In [22]:
# 从文件中恢复变量 b 的值
saver.restore(sess, './summary/test.ckpt-0')
# 查看变量 b 是否恢复成功
sess.run(b)

INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


array([1., 1., 1., 1.], dtype=float32)

In [23]:
# 从文件中恢复数据流图结构
# tf.train.import_meta_graph

## operation

In [24]:
# 常量操作
a = tf.constant(2)
b = tf.constant(3)

In [26]:
# 创建会话并执行计算操作
with tf.Session() as sess:
    print("a: %i" % sess.run(a))
    print("b: %i" % sess.run(b))
    print("Addition with constants: %i" % sess.run(a+b))
    print("Multiplication with constants: %i" % sess.run(a*b))

a: 2
b: 3
Addition with constants: 5
Multiplication with constants: 6


In [27]:
# 占位符操作
# x = tf.placeholder(dtype, shape, name)
x = tf.placeholder(tf.int16, shape=(), name="x")
y = tf.placeholder(tf.int16, shape=(), name="y")

In [28]:
# 计算操作
add = tf.add(x, y)
mul = tf.multiply(x, y)

In [29]:
# 加载默认数据流图
with tf.Session() as sess:
    # 不填充数据，直接执行操作，报错
    print("Addition with variables: %i" % sess.run(add, feed_dict={x: 10, y: 5}))
    print("Multiplication with variables: %i" % sess.run(mul, feed_dict={x: 2, y: 3}))

Addition with variables: 15
Multiplication with variables: 6


In [30]:
# 加载默认数据流图
with tf.Session() as sess:
    # 不填充数据，直接执行操作，报错
    print("Addition with variables: %i" % sess.run(add, feed_dict={x: 2, y: 3}))
    print("Multiplication with variables: %i" % sess.run(mul, feed_dict={x: 2, y: 3}))

Addition with variables: 5
Multiplication with variables: 6


## Se

In [31]:
# 创建数据流图：y = W * x + b，其中W和b为存储节点，x为数据节点。
x = tf.placeholder(tf.float32)
W = tf.Variable(1.0)
b = tf.Variable(1.0)
y = W * x + b
with tf.Session() as sess:
    tf.global_variables_initializer().run() # Operation.run
    fetch = y.eval(feed_dict={x: 3.0})      # Tensor.eval
    print(fetch)                            # fetch = 1.0 * 3.0 + 1.0

4.0
