In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

## Sequential model

In [4]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)

In [7]:
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

In [8]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.25269756, -0.8457033 ,  0.15074675,  1.1372654 ],
       [-0.25269756, -0.8457033 ,  0.15074675,  1.1372654 ],
       [-0.25269756, -0.8457033 ,  0.15074675,  1.1372654 ]],
      dtype=float32)>

In [9]:
## 等价于
# Create 3 layers
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))


In [10]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.70889735,  2.5523214 , -2.7442508 , -0.37169006],
       [ 0.70889735,  2.5523214 , -2.7442508 , -0.37169006],
       [ 0.70889735,  2.5523214 , -2.7442508 , -0.37169006]],
      dtype=float32)>

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (3, 2)                    8         
_________________________________________________________________
layer2 (Dense)               (3, 3)                    9         
_________________________________________________________________
layer3 (Dense)               (3, 4)                    16        
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [13]:
?tf.while_loop

In [15]:
i = tf.constant(100)
c = lambda i: tf.math.less(i, 2)
b = lambda i: tf.math.divide(i, 2)
r = tf.while_loop(c, b, [i])

In [16]:
r

[<tf.Tensor: shape=(), dtype=int32, numpy=100>]