In [1]:
import numpy as np

In [2]:
p = 0.5

In [3]:
X = np.random.randn(4,5)
X 

array([[-0.1527091 , -1.48465321, -0.81871301, -0.21595529,  0.07761352],
       [ 0.52384147,  0.54482058, -0.11061767,  0.47315143,  0.38518605],
       [ 0.82399297, -0.26839995, -1.77223741,  0.27055547,  0.32859292],
       [-0.8757897 ,  1.19174568, -0.21235382,  0.49061418,  1.55863396]])

In [4]:
W1 = np.random.randn(10,4)
W1

array([[ 1.66505474, -0.21536391, -0.59714192, -0.2025333 ],
       [-2.084639  ,  0.49138969,  2.17601159, -1.11766097],
       [ 0.5598689 , -0.93375321,  0.6060111 ,  0.96968898],
       [ 0.6201963 ,  0.63180377,  0.54716499, -0.8969039 ],
       [-0.78136411,  1.26312214, -0.22784386, -1.14488839],
       [ 0.56132686, -0.69573653,  0.36827275, -1.1377372 ],
       [-0.35862874,  0.30966537,  1.03198642,  0.66531483],
       [ 1.83092648,  0.62747046,  0.34122951,  0.9328817 ],
       [ 0.71389179,  0.71534773,  0.16125895,  0.64998715],
       [ 0.01399478, -1.42493915,  0.1818278 , -0.7690498 ]])

In [5]:
x = np.dot(W1, X)
x

array([[-0.68174973, -2.67045887, -0.23809294, -0.72240284, -0.4656163 ],
       [ 3.34760786,  1.44667617, -1.96670488,  0.72308207, -0.99952205],
       [-0.92453046, -0.34696981, -1.63499507,  0.07698947,  1.39430582],
       [ 1.4726147 , -1.79229714, -1.35689674, -0.12699111, -0.92665272],
       [ 1.59593689,  0.54496715,  1.14690418,  0.14304488, -1.43343719],
       [ 0.84969731, -2.66716508, -0.79366876, -0.90896204, -1.87672547],
       [ 0.48465511,  1.21705234, -1.71084754,  0.82958885,  1.46753006],
       [-0.48674155, -1.3562603 , -2.37125334,  0.45149679,  1.9499442 ],
       [-0.17066478,  0.06119191, -1.08741898,  0.5468215 ,  1.39703021],
       [ 0.07477137, -1.76242791, -0.01276563, -1.00534648, -1.6867003 ]])

In [6]:
x.shape

(10, 5)

In [7]:
z = np.maximum(0, x)
z

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [3.34760786, 1.44667617, 0.        , 0.72308207, 0.        ],
       [0.        , 0.        , 0.        , 0.07698947, 1.39430582],
       [1.4726147 , 0.        , 0.        , 0.        , 0.        ],
       [1.59593689, 0.54496715, 1.14690418, 0.14304488, 0.        ],
       [0.84969731, 0.        , 0.        , 0.        , 0.        ],
       [0.48465511, 1.21705234, 0.        , 0.82958885, 1.46753006],
       [0.        , 0.        , 0.        , 0.45149679, 1.9499442 ],
       [0.        , 0.06119191, 0.        , 0.5468215 , 1.39703021],
       [0.07477137, 0.        , 0.        , 0.        , 0.        ]])

In [8]:
u1 = np.random.rand(*z.shape)
drop = u1 < p
drop

array([[False,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True,  True,  True, False, False],
       [False, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [False, False, False,  True,  True]])

In [9]:
z*drop

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [3.34760786, 1.44667617, 0.        , 0.72308207, 0.        ],
       [0.        , 0.        , 0.        , 0.07698947, 1.39430582],
       [1.4726147 , 0.        , 0.        , 0.        , 0.        ],
       [1.59593689, 0.54496715, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.48465511, 1.21705234, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.45149679, 0.        ],
       [0.        , 0.06119191, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [10]:
def train_step(X):
    """ X contains the data """
  
    # 三层神经网络前向传播为例
    H1 = np.maximum(0, np.dot(W1, X) + b1)
    U1 = np.random.rand(*H1.shape) < p   # 随机隐藏p
    H1 *= U1 # drop!
    H2 = np.maximum(0, np.dot(W2, H1) + b2)
    U2 = np.random.rand(*H2.shape) < p # second dropout mask
    H2 *= U2 # drop!
    out = np.dot(W3, H2) + b3
    
def predict(X):
    # ensembled forward pass
    H1 = np.maximum(0, np.dot(W1, X) + b1) * p    # NOTE: scale the activations
    H2 = np.maximum(0, np.dot(W2, H1) + b2) * p   # NOTE: scale the activations
    out = np.dot(W3, H2) + b3