## FocalLoss

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [5]:
class FocalLoss(nn.Module):

    def __init__(self, weight=None, reduction='mean', gamma=0, eps=1e-7):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.eps = eps
        self.ce = torch.nn.CrossEntropyLoss(weight=weight, reduction=reduction)

    def forward(self, input, target):
        logp = self.ce(input, target)
        p = torch.exp(-logp)
        loss = (1 - p) ** self.gamma * logp
        return loss.mean()

In [15]:
# 假设词汇表的大小为3， 语料包含两个单词"2 0"
y = [2, 0, 1, 1]
# 假设模型对两个单词预测时，产生的logit分别是[2.0, -1.0, 3.0]和[1.0, 0.0, -0.5]
y_logits = [[2.0, -1.0, 3.0], [1.0, 0.0, -0.5], [2.0, 1.0, -0.5], [1, 8, 2]]

In [16]:
F.cross_entropy(torch.tensor(y_logits), torch.tensor(y,dtype=torch.int64))

tensor(0.5415)

In [19]:
FocalLoss(weight=torch.Tensor([2, 2, 2]), gamma=2)(torch.tensor(y_logits), torch.tensor(y,dtype=torch.int64))

tensor(0.0947)

In [20]:
?nn.LSTM

In [21]:
?nn.GRU

In [22]:
F.binary_cross_entropy(torch.tensor(y_logits), torch.tensor(y,dtype=torch.int64))

/usr/local/anaconda2/envs/pt-tf-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 3])) is deprecated. Please ensure they have the same size.
  """Entry point for launching an IPython kernel.


ValueError: Target and input must have the same number of elements. target nelement (4) != input nelement (12)

In [23]:
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
input

tensor([0.5983, 1.0153, 0.4514], requires_grad=True)

In [24]:
target = torch.empty(3).random_(2)
target

tensor([1., 1., 1.])

In [25]:
m(input)

tensor([0.6453, 0.7341, 0.6110], grad_fn=<SigmoidBackward>)

In [27]:
output = loss(m(input), target)

In [28]:
output

tensor(0.4133, grad_fn=<BinaryCrossEntropyBackward>)

In [29]:
output.backward()

In [32]:
?nn.BCELoss

In [ ]:
def 