In [1]:
import torch
import torch.nn as nn

In [2]:
# torch.squeeze #删掉 Tensor 中大小为 1 的维度，作用类似于 numpy 中的 flatten()
# torch.unsqueeze 与 squeeze 进行相反的操作，在参数指定的维度添加一个大小为 1 的维度。
# torch.bmm 对同一个 batch 里的两个矩阵求 dot product。 
# torch.gather：根据指定的 dimension 以及 index，从一个 tensor 里取出相应位置的值。
# torch.mul(a, b)是矩阵a和b对应位相乘，a和b的维度必须相等，比如a的维度是(1, 2)，b的维度是(1, 2)，返回的仍是(1, 2)的矩阵
# torch.mm(a, b)是矩阵a和b矩阵相乘，比如a的维度是(1, 2)，b的维度是(2, 3)，返回的就是(1, 3)的矩阵
# torch.cat
# torch.ne

In [6]:
x = torch.rand(2,3,4)
x

tensor([[[0.7718, 0.3268, 0.6563, 0.6734],
         [0.0300, 0.1208, 0.4878, 0.3113],
         [0.0475, 0.8181, 0.2984, 0.2245]],

        [[0.4115, 0.2112, 0.9286, 0.1050],
         [0.5111, 0.8850, 0.4168, 0.8963],
         [0.8428, 0.1368, 0.0164, 0.0590]]])

In [9]:
x.sum(dim=0)

tensor([[1.1833, 0.5380, 1.5849, 0.7784],
        [0.5411, 1.0058, 0.9046, 1.2076],
        [0.8904, 0.9550, 0.3148, 0.2835]])

In [6]:
l = (2, 3)

In [7]:
inp = torch.rand(8, 2)

In [8]:
inp

tensor([[0.8449, 0.6102],
        [0.9377, 0.8641],
        [0.6881, 0.4788],
        [0.9713, 0.9298],
        [0.5647, 0.5123],
        [0.7810, 0.6936],
        [0.3875, 0.2114],
        [0.4120, 0.6362]])

In [9]:
l.weight

Parameter containing:
tensor([[-0.6362, -0.7021],
        [-0.4267, -0.6269],
        [ 0.3059, -0.3417]], requires_grad=True)

In [10]:
l.bias

Parameter containing:
tensor([-0.2412,  0.6470,  0.1694], requires_grad=True)

In [11]:
y = l(inp)

In [12]:
y

tensor([[-1.2071, -0.0961,  0.2194],
        [-1.4445, -0.2949,  0.1610],
        [-1.0151,  0.0532,  0.2163],
        [-1.5120, -0.3504,  0.1489],
        [-0.9601,  0.0849,  0.1671],
        [-1.2251, -0.1211,  0.1713],
        [-0.6361,  0.3491,  0.2157],
        [-0.9500,  0.0723,  0.0781]], grad_fn=<AddmmBackward>)

In [28]:
torch.mm(inp, l.weight.t()) 

tensor([[-0.9659, -0.7430,  0.0500],
        [-1.2033, -0.9418, -0.0083],
        [-0.7739, -0.5938,  0.0469],
        [-1.2708, -0.9973, -0.0205],
        [-0.7189, -0.5621, -0.0023],
        [-0.9839, -0.7681,  0.0020],
        [-0.3950, -0.2979,  0.0463],
        [-0.7088, -0.5746, -0.0913]], grad_fn=<MmBackward>)

In [27]:
inp[0].size()

torch.Size([2])

In [29]:
a = torch.tensor([[0.8449, 0.6102]])

In [30]:
a.size()

torch.Size([1, 2])

In [35]:
b = l.weight.t()

In [38]:
b.size()

torch.Size([2, 3])

In [41]:
torch.mm(a, b) + l.bias

tensor([[-1.2071, -0.0961,  0.2194]], grad_fn=<AddBackward0>)

In [42]:
b

tensor([[-0.6362, -0.4267,  0.3059],
        [-0.7021, -0.6269, -0.3417]], grad_fn=<TBackward>)

In [43]:
inp[0]

tensor([0.8449, 0.6102])

In [45]:
inp[0][0] * b[0][0] + inp[0][1]*b[1][0] + l.bias[0]

tensor(-1.2071, grad_fn=<AddBackward0>)

In [47]:
torch.mm(inp, b) + l.bias

tensor([[-1.2071, -0.0961,  0.2194],
        [-1.4445, -0.2949,  0.1610],
        [-1.0151,  0.0532,  0.2163],
        [-1.5120, -0.3504,  0.1489],
        [-0.9601,  0.0849,  0.1671],
        [-1.2251, -0.1211,  0.1713],
        [-0.6361,  0.3491,  0.2157],
        [-0.9500,  0.0723,  0.0781]], grad_fn=<AddBackward0>)