In [2]:
import torch

## torch tensor常用操作

In [3]:
x = torch.tensor([[1,2,3,4],
                  [4,3,2,1]], 
                 dtype=torch.float32)
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [4]:
x.argmax(dim=1)  # 按照列，实际上就是行

tensor([3, 0])

In [5]:
x.softmax(dim=1)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.6439, 0.2369, 0.0871, 0.0321]])

In [6]:
y = torch.randn(1,4)
y

tensor([[-0.3004, -1.6971,  0.0836,  0.5095]])

In [7]:
torch.cat((x, y), dim=0)  # 合并，其余维度相同

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [-0.3004, -1.6971,  0.0836,  0.5095]])

In [8]:
# squeeze 挤压
x.unsqueeze(dim=0).size()

torch.Size([1, 2, 4])

In [9]:
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [18]:
x.permute(1,0)  #转置, 相当于更灵活的transpose

tensor([[1., 4.],
        [2., 3.],
        [3., 2.],
        [4., 1.]])

In [11]:
x.reshape(2,1,4)

tensor([[[1., 2., 3., 4.]],

        [[4., 3., 2., 1.]]])

In [13]:
x.reshape(4,2)

tensor([[1., 2.],
        [3., 4.],
        [4., 3.],
        [2., 1.]])

In [15]:
x.view(-1, 8)

tensor([[1., 2., 3., 4., 4., 3., 2., 1.]])

In [16]:
x.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [4., 3.],
        [2., 1.]])

In [17]:
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])