In [2]:
import torch

# torch tensor常用操作

In [3]:
x = torch.tensor([[1,2,3,4],
                  [4,3,2,1]], 
                 dtype=torch.float32)
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

## x.argmax(dim=n) 
- 按照维度，取最大值的索引

In [4]:
x.argmax(dim=1)  # 按照列，实际上就是行

tensor([3, 0])

## x.softmax(dim=n)
- 相加得1的概率分布

In [5]:
x.softmax(dim=1)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.6439, 0.2369, 0.0871, 0.0321]])

In [6]:
y = torch.randn(1,4)
y

tensor([[ 0.2823,  0.0590,  0.5251, -0.8787]])

## torch.cat((x, y), dim=0)
- 对数据沿着某一维度进行拼接。
- cat后数据的总维数不变。
- 比如下面代码对两个2维tensor（分别为2*4,1*4）进行拼接，拼接完后变为3*4还是2维的tensor。

In [7]:
torch.cat((x, y), dim=0)  # 合并，其余维度相同

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [ 0.2823,  0.0590,  0.5251, -0.8787]])

## torch.stack() 增加新的维度进行堆叠
- stack则会增加新的维度。
- 如对两个1*2维的tensor在第0个维度上stack，则会变为2*1*2的tensor；在第1个维度上stack，则会变为1*2*2的tensor。

In [8]:
a = torch.randn(1,2)
a

tensor([[1.8498, 0.7072]])

In [9]:
b = torch.randn(1,2)
b

tensor([[-0.1119,  0.3021]])

In [10]:
c = torch.stack((a, b), dim=0)
c

tensor([[[ 1.8498,  0.7072]],

        [[-0.1119,  0.3021]]])

In [11]:
c.size()

torch.Size([2, 1, 2])

In [12]:
d = torch.stack((a, b), dim=1)
d

tensor([[[ 1.8498,  0.7072],
         [-0.1119,  0.3021]]])

## transpose 交换维度
- 维度互换，只能两个维度

In [13]:
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [14]:
x.transpose(0,1)

tensor([[1., 4.],
        [2., 3.],
        [3., 2.],
        [4., 1.]])

In [15]:
x.transpose(1,0)

tensor([[1., 4.],
        [2., 3.],
        [3., 2.],
        [4., 1.]])

In [16]:
x = torch.randn(2,3,5)
x

tensor([[[ 0.4872,  0.5975, -0.8057,  0.3031, -1.0987],
         [-1.0421,  0.6513, -0.7745,  0.1754,  0.0581],
         [-0.2965,  0.4918,  2.1815, -0.9391, -1.8107]],

        [[-0.3925, -0.4663, -0.6166,  0.7119,  1.1318],
         [ 0.0022,  0.2829,  0.1346, -0.1836, -0.9966],
         [ 0.8951, -0.8710,  0.9616, -0.0181, -0.4105]]])

In [17]:
x.transpose(1,2)

tensor([[[ 0.4872, -1.0421, -0.2965],
         [ 0.5975,  0.6513,  0.4918],
         [-0.8057, -0.7745,  2.1815],
         [ 0.3031,  0.1754, -0.9391],
         [-1.0987,  0.0581, -1.8107]],

        [[-0.3925,  0.0022,  0.8951],
         [-0.4663,  0.2829, -0.8710],
         [-0.6166,  0.1346,  0.9616],
         [ 0.7119, -0.1836, -0.0181],
         [ 1.1318, -0.9966, -0.4105]]])

In [18]:
x.transpose(1,2).size()

torch.Size([2, 5, 3])

## x.permute()
- 适合多维数据，更灵活的transpose
- permute是更灵活的transpose，可以灵活的对原数据的维度进行调换，而数据本身不变。

In [19]:
x = torch.randn(2,3,5)
x

tensor([[[ 1.8330, -1.4699,  0.2724, -1.3835,  1.7805],
         [ 0.9402, -0.5081,  1.7123,  0.4500,  1.5685],
         [ 0.2564, -0.5939, -0.4169,  0.1397,  1.5533]],

        [[ 0.3046, -0.6120,  1.9476,  1.0779, -0.2214],
         [ 2.3662, -0.1200,  0.5632,  2.2650, -0.0854],
         [-0.4841,  0.6712,  0.8351, -0.8841,  1.8521]]])

In [20]:
y = x.permute(1,2,0)
y.size()

torch.Size([3, 5, 2])

In [21]:
y

tensor([[[ 1.8330,  0.3046],
         [-1.4699, -0.6120],
         [ 0.2724,  1.9476],
         [-1.3835,  1.0779],
         [ 1.7805, -0.2214]],

        [[ 0.9402,  2.3662],
         [-0.5081, -0.1200],
         [ 1.7123,  0.5632],
         [ 0.4500,  2.2650],
         [ 1.5685, -0.0854]],

        [[ 0.2564, -0.4841],
         [-0.5939,  0.6712],
         [-0.4169,  0.8351],
         [ 0.1397, -0.8841],
         [ 1.5533,  1.8521]]])

## x.reshape()
- 数据不变，改变tensor的形状

In [22]:
x.shape

torch.Size([2, 3, 5])

In [23]:
x.reshape(3,1,10)

tensor([[[ 1.8330, -1.4699,  0.2724, -1.3835,  1.7805,  0.9402, -0.5081,
           1.7123,  0.4500,  1.5685]],

        [[ 0.2564, -0.5939, -0.4169,  0.1397,  1.5533,  0.3046, -0.6120,
           1.9476,  1.0779, -0.2214]],

        [[ 2.3662, -0.1200,  0.5632,  2.2650, -0.0854, -0.4841,  0.6712,
           0.8351, -0.8841,  1.8521]]])

In [24]:
x.reshape(5,6)

tensor([[ 1.8330, -1.4699,  0.2724, -1.3835,  1.7805,  0.9402],
        [-0.5081,  1.7123,  0.4500,  1.5685,  0.2564, -0.5939],
        [-0.4169,  0.1397,  1.5533,  0.3046, -0.6120,  1.9476],
        [ 1.0779, -0.2214,  2.3662, -0.1200,  0.5632,  2.2650],
        [-0.0854, -0.4841,  0.6712,  0.8351, -0.8841,  1.8521]])

## x.view()
- 改变形状

In [25]:
x.view(-1, 2, 3)

tensor([[[ 1.8330, -1.4699,  0.2724],
         [-1.3835,  1.7805,  0.9402]],

        [[-0.5081,  1.7123,  0.4500],
         [ 1.5685,  0.2564, -0.5939]],

        [[-0.4169,  0.1397,  1.5533],
         [ 0.3046, -0.6120,  1.9476]],

        [[ 1.0779, -0.2214,  2.3662],
         [-0.1200,  0.5632,  2.2650]],

        [[-0.0854, -0.4841,  0.6712],
         [ 0.8351, -0.8841,  1.8521]]])

In [26]:
x.view(-1, 15)

tensor([[ 1.8330, -1.4699,  0.2724, -1.3835,  1.7805,  0.9402, -0.5081,  1.7123,
          0.4500,  1.5685,  0.2564, -0.5939, -0.4169,  0.1397,  1.5533],
        [ 0.3046, -0.6120,  1.9476,  1.0779, -0.2214,  2.3662, -0.1200,  0.5632,
          2.2650, -0.0854, -0.4841,  0.6712,  0.8351, -0.8841,  1.8521]])

In [27]:
x

tensor([[[ 1.8330, -1.4699,  0.2724, -1.3835,  1.7805],
         [ 0.9402, -0.5081,  1.7123,  0.4500,  1.5685],
         [ 0.2564, -0.5939, -0.4169,  0.1397,  1.5533]],

        [[ 0.3046, -0.6120,  1.9476,  1.0779, -0.2214],
         [ 2.3662, -0.1200,  0.5632,  2.2650, -0.0854],
         [-0.4841,  0.6712,  0.8351, -0.8841,  1.8521]]])

## x.unsqueeze/squeeze
- squeeze(dim_n)压缩，即去掉元素数量为1的dim_n维度。
- 同理unsqueeze(dim_n)，增加dim_n维度，元素数量为1。

In [28]:
x = torch.randn(5,1,3)
x.size()

torch.Size([5, 1, 3])

In [29]:
x.squeeze(dim=1).size()

torch.Size([5, 3])

In [30]:
# squeeze 挤压
x.unsqueeze(dim=0).size()

torch.Size([1, 5, 1, 3])