In [1]:
import torch

## 

In [2]:
x = torch.tensor([[1,2,3,4],
                  [4,3,2,1]], 
                 dtype=torch.float32)
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [7]:
x.argmax(dim=1)  # 按照列，实际上就是行

tensor([3, 0])

In [8]:
x.softmax(dim=1)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.6439, 0.2369, 0.0871, 0.0321]])

In [10]:
y = torch.randn(1,4)
y

tensor([[ 1.2934, -1.8192,  0.5061, -1.4826]])

In [11]:
torch.cat((x, y), dim=0)  # 合并，其余维度相同

tensor([[ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [ 1.2934, -1.8192,  0.5061, -1.4826]])

In [12]:
# squeeze 挤压
x.unsqueeze(dim=0).size()

torch.Size([1, 2, 4])

In [15]:
x

tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [16]:
x.permute(1,0)  #转置？

tensor([[1., 4.],
        [2., 3.],
        [3., 2.],
        [4., 1.]])

In [18]:
?x.permute