## 激活函数

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 内容
- TORCH.ERF

## sigmoid
- 激活函数作用于每一个神经元的输出。不会改变input向量的形状。

In [9]:
x = torch.rand(1, 10, 16)

In [10]:
x

tensor([[[0.5782, 0.0230, 0.7456, 0.4203, 0.1493, 0.3453, 0.5130, 0.3699,
          0.1696, 0.6518, 0.8739, 0.1157, 0.1473, 0.0737, 0.3562, 0.9762],
         [0.5642, 0.3309, 0.8848, 0.4427, 0.1640, 0.0444, 0.0771, 0.7839,
          0.9040, 0.3694, 0.4052, 0.6492, 0.4957, 0.8787, 0.1721, 0.8748],
         [0.5123, 0.8563, 0.8330, 0.0144, 0.6705, 0.4136, 0.0407, 0.1077,
          0.0544, 0.8007, 0.2540, 0.7208, 0.8726, 0.1913, 0.3542, 0.9049],
         [0.7295, 0.8702, 0.5192, 0.7430, 0.4548, 0.3618, 0.6090, 0.9520,
          0.1672, 0.7171, 0.1116, 0.4045, 0.3093, 0.5125, 0.9203, 0.7449],
         [0.2572, 0.5132, 0.4487, 0.4460, 0.5461, 0.7483, 0.7185, 0.6658,
          0.2664, 0.7929, 0.9170, 0.9496, 0.6378, 0.5290, 0.9367, 0.4175],
         [0.8098, 0.9190, 0.3316, 0.1591, 0.7459, 0.1523, 0.3028, 0.8776,
          0.0747, 0.2070, 0.4130, 0.7787, 0.0840, 0.1881, 0.9634, 0.7586],
         [0.0241, 0.0882, 0.5890, 0.8219, 0.2709, 0.5569, 0.5990, 0.0539,
          0.7669, 0.7808, 0.5628

In [13]:
y = F.sigmoid(x)
y

tensor([[[0.6407, 0.5057, 0.6782, 0.6036, 0.5373, 0.5855, 0.6255, 0.5914,
          0.5423, 0.6574, 0.7056, 0.5289, 0.5368, 0.5184, 0.5881, 0.7264],
         [0.6374, 0.5820, 0.7078, 0.6089, 0.5409, 0.5111, 0.5193, 0.6865,
          0.7118, 0.5913, 0.5999, 0.6568, 0.6214, 0.7066, 0.5429, 0.7057],
         [0.6254, 0.7019, 0.6970, 0.5036, 0.6616, 0.6020, 0.5102, 0.5269,
          0.5136, 0.6901, 0.5631, 0.6728, 0.7053, 0.5477, 0.5876, 0.7120],
         [0.6747, 0.7048, 0.6270, 0.6777, 0.6118, 0.5895, 0.6477, 0.7215,
          0.5417, 0.6720, 0.5279, 0.5998, 0.5767, 0.6254, 0.7151, 0.6781],
         [0.5640, 0.6256, 0.6103, 0.6097, 0.6332, 0.6788, 0.6723, 0.6606,
          0.5662, 0.6885, 0.7144, 0.7210, 0.6542, 0.6292, 0.7184, 0.6029],
         [0.6921, 0.7148, 0.5822, 0.5397, 0.6783, 0.5380, 0.5751, 0.7063,
          0.5187, 0.5516, 0.6018, 0.6854, 0.5210, 0.5469, 0.7238, 0.6810],
         [0.5060, 0.5220, 0.6431, 0.6946, 0.5673, 0.6357, 0.6454, 0.5135,
          0.6828, 0.6858, 0.6371

In [14]:
y.size()

torch.Size([1, 10, 16])

In [23]:
m = nn.Sigmoid()
inputs = torch.randn(2)
inputs

tensor([-0.3526, -0.0831])

In [33]:
outputs = m(inputs)

In [34]:
outputs

tensor([0.4127, 0.4792])

In [36]:
def sigmoid(x):
    return 1./ (1. + torch.exp(-x))

In [41]:
sigmoid(inputs)

tensor([0.4127, 0.4792])